// ── Derive the PresenceStrip client payload ──────────────────────────────
// The full canon presence map is ~4.6 MB serialised, which is far too heavy
// to ship as a client-component prop in the article's RSC payload. This
// script trims it to the strip's selectable set (characters, ≥2 mentions,
// top 60 by mention count) with tooltip snippets, and writes it as a
// TypeScript module under lib/derived/. The article loads that module inside
// a lazily-imported client chunk, so it never touches the critical path.
//
// Re-run after a re-ingest or re-aggregation:  npm run derive:presence
import { writeFileSync, mkdirSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { loadCanonData } from "../lib/canon-aggregate";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "lib", "derived", "presence-strip-data.ts");

const SNIPPET_LENGTH = 140;

const canon = loadCanonData();

// Mirror PresenceStrip's own selection rule so the picker sees the same list.
const selectable = canon.entities
  .filter((e) => e.type === "character" && e.totalMentions >= 2)
  .slice(0, 60);
const selectableKeys = new Set(selectable.map((e) => e.key));

const presence: Record<string, { byWork: Record<string, { position: number; sentenceText: string }[]> }> = {};
for (const [key, forEntity] of Object.entries(canon.presence)) {
  if (!selectableKeys.has(key)) continue;
  presence[key] = {
    byWork: Object.fromEntries(
      Object.entries(forEntity.byWork).map(([slug, marks]) => [
        slug,
        marks.map((m) => ({
          position: Math.round(m.position * 10000) / 10000,
          sentenceText:
            m.sentenceText.length > SNIPPET_LENGTH
              ? m.sentenceText.slice(0, SNIPPET_LENGTH - 1) + "…"
              : m.sentenceText,
        })),
      ])
    ),
  };
}

const payload = { entities: selectable, presence };
const json = JSON.stringify(payload);

// Emit as a JSON.parse of a string literal rather than an object literal or
// .json module — a single string parses fast in both tsc and the bundler,
// and the explicit cast keeps the type checker out of a megabyte of data.
const source = `// AUTO-GENERATED by scripts/derive-presence-strip.ts — do not edit.
// Regenerate with: npm run derive:presence
import type { EntitySummary } from "../canon-types";

export interface StripMark {
  position: number;
  sentenceText: string;
}

export interface PresenceStripData {
  entities: EntitySummary[];
  presence: Record<string, { byWork: Record<string, StripMark[]> }>;
}

const json = ${JSON.stringify(json)};

const data = JSON.parse(json) as PresenceStripData;
export default data;
`;

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, source);
console.log(
  `wrote ${OUT} — ${(source.length / 1024).toFixed(0)} KB, ${selectable.length} characters, ` +
    `${Object.values(presence).reduce((s, p) => s + Object.values(p.byWork).reduce((n, m) => n + m.length, 0), 0)} marks`
);
